variable "vpc" {}
variable "env" {}
variable "app" {}
variable "bastion_cidr_block" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_vpc_rtid" {}
variable "kms_arn" {}
variable "docdb" {}
variable "rds" {}
variable "elasticache" {}
variable "rabbitmq" {}
